version: 2
jobs:
  hygiene_tests:
    working_directory: /git/dsa-open
    docker:
      - image: docker/compose:debian-1.26.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start hygiene container
          command: |
            bash .hygiene/start-container.sh
      - run:
          name: Create needed dirs in the hygiene container
          command: |
            bash .hygiene/create-directories.sh
      - run:
          name: Copy and organize git repo in hygiene container
          command: |
            bash .hygiene/copy-to-container.sh
      - run:
          name: Run hygiene tests
          command: |
            docker exec hygiene /publisher/publish.sh hygiene
      - run:
          name: Copy tests results back
          command: |
            docker cp hygiene:/output/dsa-open /output
      - run:
          name: Stop the hygiene container
          command: |
            cd .hygiene/docker/compose/hygiene && docker-compose down
workflows:
  version: 2
  build_and_test:
    jobs:
      - hygiene_tests
